# Generated by Django 5.1.5 on 2025-01-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scanned_recipes/', verbose_name='Zeskanowany obraz')),
                ('scanned_text', models.TextField(blank=True, null=True, verbose_name='Rozpoznany tekst')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
